name: Build and Deploy Microservice

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'ci: update image tag')"
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: camilonr03/microservice-app

    steps:
      - name: Checkout con token personalizado
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Obtener hash corto del commit
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login a Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push de la imagen Docker
        run: |
          docker build -t $IMAGE_NAME:${{ env.SHORT_SHA }} MicroServicios_Poc
          docker push $IMAGE_NAME:${{ env.SHORT_SHA }}

      - name: Reemplazar tag en values.yaml
        run: |
          sed -i "s/^  tag: .*/  tag: ${{ env.SHORT_SHA }}/" MicroServicios_Poc/helm/values.yaml

      - name: Debug values.yaml
        run: cat MicroServicios_Poc/helm/values.yaml

      - name: Commit y push de nuevo tag
        run: |
          git config user.name "CamiloN03"
          git config user.email "camilo03.navarrete03@gmail.com"
          git add MicroServicios_Poc/helm/values.yaml
          git commit -m "ci: update image tag to ${{ env.SHORT_SHA }}" || echo "No changes to commit"
          git push origin develop
